name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Restore/create node_modules cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-json.lock') }}

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm test

      - name: Integration test deno
        run: npm run test:integration:deno

  integration-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["12", "14"]

    name: Node ${{ matrix.node }} integration test

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Integration test node version ${{ matrix.node }}
        run: npm run test:integration:node
